# 开发环境

# 端口号
server:
  port: 8091

spring:
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_lg?serverTimezone=GMT%2B8&useSSL=true&characterEncoding=utf-8
    username: root
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: localhost
      port: 6379
#      邮件
  mail:
    username: 2172941774@qq.com #账号
    password: tsgdqurawjkjeaaj    #在账号所在的服务商开启smtp服务并要取smtp密码
    host: smtp.qq.com    #邮箱的SMTP
    spring:
      mail:
        properties:
          mail:
            smtp:
              ssl:
                enable: true    #开启加密验证

# mybatisPlus
mybatis-plus:
  mapper-locations: classpath*:com/douk/muses/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0