# 开发环境

# 端口号
server:
  port: 8091

spring:
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://home.007666.xyz:3306/db-lg?serverTimezone=GMT%2B8&useSSL=true&characterEncoding=utf-8
    username: root
    password: zengyuan
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: redis-17840.c54.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 17840
      username: default
      password: oAKf5PdxmjSgU6mhLigYAt6ZdIg7KJmC
  #      邮件
  mail:
    username: 2172941774@qq.com #账号
    password: tsgdqurawjkjeaaj    #在账号所在的服务商开启smtp服务并要取smtp密码
    host: smtp.qq.com    #邮箱的SMTP
    spring:
      mail:
        properties:
          mail:
            smtp:
              ssl:
                enable: true    #开启加密验证
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

files:
  upload:
    path: D:\
mybatis-plus:
  mapper-locations: classpath*:com/douk/muses/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0